apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: hobbyfarm-install
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "create", "update"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "create", "update", "delete"]
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "services"]
      verbs: ["get", "create", "update", "delete"]
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "create", "update", "delete"]
    - apiGroups: ["rbac.authorization.k8s.io"]
      resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
      verbs: ["get", "create", "update", "delete"]